### ISSUE TITLE
Q: control multiple m27q monitors

### ISSUE THREAD

**Issue by crujonescheated** [P403n1x87/m27q#2]
Created a Github account just to comment on this, so if I'm leaving this in the wrong area I do apologize. I have been searching for a way to select the input on my 3 m27q monitors independently from my Windows machine for quite some time. As you probably already know, the OSD Sidekick app will only control one monitor. Would this even be possible?  I'm by no means a coder.

**Comment by P403n1x87** [comment]
If I understand your problem correctly, I think there is a branch in a fork that does just that: https://github.com/Lochnair/m27q/tree/multiple-monitors

**Comment by crujonescheated** [comment]
That is amazing, thank you.
