### ISSUE TITLE
Ways to switch inputs?

### ISSUE THREAD

**Issue by kerv** [P403n1x87/m27q#4]
Another question - not an issue really.

On my monitor, I have a displayport and hdmi connected (not using USB-C or the KVM switch... since it seems to only work with the USB-C). If I attached a USB-C cord to run a script like this, could I modify the script to tell the monitor to switch inputs between the Displayport and HDMI?

My old BenQ monitor had a DDC/CI capabilities that allowed me to do this... which I really miss...

**Comment by AlexVdberg** [comment]
You should be able to use DDC to do this.
I have the M28U and am using ddcutil to switch between inputs. The only time it doesn't work is when the display is asleep, but I think that is a bug in my wrapper script and not ddcutil.

**Comment by kerv** [comment]
Thanks for the response... and sorry - I must be out of the loop. Where can I find the ddcutil?

Oh, sorry. Been a long day. I assume you're talking about http://www.ddcutil.com/

**Comment by AlexVdberg** [comment]
yeah, that's the one.
I just installed it through my package manager, so `apt install ddcutil` or `pacman -Syu ddcutil` for Ubuntu and Manjaro respectively.

**Comment by kerv** [comment]
Thanks @AlexVdberg ddcutil does work great for my M32U! Now to script some stuff around connecting USB devices to trigger the switch. Thanks again!
